package fr.efrei.tp1.bo;

import java.io.Serializable;
import java.util.Comparator;

import androidx.annotation.NonNull;

//This class is used in order to represnt a User
final public class User
    implements Serializable
{

  //This class is used in order to sort a user
  public static final class UserComparator
      implements Comparator<User>
  {

    @Override
    public int compare(User o1, User o2)
    {
      return o1.name.compareTo(o2.name);
    }

  }

  @NonNull
  public final String name;

  @NonNull
  public final String phoneNumer;

  @NonNull
  public final String address;

  @NonNull
  public final String about;

  public User(@NonNull String name, @NonNull String phoneNumer, @NonNull String address,
      @NonNull String about)
  {
    this.name = name;
    this.phoneNumer = phoneNumer;
    this.address = address;
    this.about = about;
  }

  //The methods "equals" and "hashcode" has been
  //automatically generated by Android Studio
  //They are used in order to compare users (sort + deletion)
  @Override
  public boolean equals(Object o)
  {
    if (this == o)
    {
      return true;
    }
    if (!(o instanceof User))
    {
      return false;
    }

    User user = (User) o;

    if (!name.equals(user.name))
    {
      return false;
    }
    if (!phoneNumer.equals(user.phoneNumer))
    {
      return false;
    }
    if (!address.equals(user.address))
    {
      return false;
    }
    return about.equals(user.about);
  }

  @Override
  public int hashCode()
  {
    int result = name.hashCode();
    result = 31 * result + phoneNumer.hashCode();
    result = 31 * result + address.hashCode();
    result = 31 * result + about.hashCode();
    return result;
  }
}
